### ISSUE TITLE
NodeJS and cljsjs.react.dom issue

### ISSUE THREAD

**Issue by alex-glv** [cljsjs/packages#923]
Requiring cljsjs.react.dom seem to cause an issue with :target :nodejs 
Error being:
```
$ java -cp $(lein classpath) clojure.main node.clj && node main.js
module.js:442
    throw err;
    ^

Error: Cannot find module 'react'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at /Users/a/Sites/nodejs-cljs/out/react-dom.inc.js:16:24
    at Object.<anonymous> (/Users/a/Sites/nodejs-cljs/out/react-dom.inc.js:40:3)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
```

Reproduce by checking out the repo:
https://github.com/alex-glv/nodejs-cljs

Then
```$ java -cp $(lein classpath) clojure.main node.clj && node main.js```

Any ideas what might be causing it?

**Comment by alex-glv** [comment]
Here's a NODE_DEBUG=module log that shows requiring react works only outside of react.dom at some point, and then fails from react.dom
```
[...]
MODULE 42814: looking for "/Users/a/Sites/nodejs-cljs/out/react.inc.js" in ["/Users/a/Sites/nodejs-cljs/out/goog/bootstrap"]
MODULE 42814: load "/Users/a/Sites/nodejs-cljs/out/react.inc.js" for module "/Users/a/Sites/nodejs-cljs/out/react.inc.js"
MODULE 42814: Module._load REQUEST ../../react-dom.inc.js parent: /Users/a/Sites/nodejs-cljs/out/goog/bootstrap/nodejs.js
MODULE 42814: RELATIVE: requested: ../../react-dom.inc.js set ID to: /Users/a/Sites/nodejs-cljs/out/react-dom.inc.js from /Users/a/Sites/nodejs-cljs/out/goog/bootstrap/nodejs.js
MODULE 42814: looking for "/Users/a/Sites/nodejs-cljs/out/react-dom.inc.js" in ["/Users/sashka/Sites/nodejs-cljs/out/goog/bootstrap"]
MODULE 42814: load "/Users/a/Sites/nodejs-cljs/out/react-dom.inc.js" for module "/Users/a/Sites/nodejs-cljs/out/react-dom.inc.js"
MODULE 42814: Module._load REQUEST react parent: /Users/a/Sites/nodejs-cljs/out/react-dom.inc.js
MODULE 42814: looking for "react" in ["/Users/a/Sites/nodejs-cljs/out/node_modules","/Users/a/Sites/nodejs-cljs/node_modules","/Users/a/Sites/node_modules","/Users/a/node_modules","/Users/node_modules","/usr/lib/node_modules","/usr/lib/node_modules","./","/Users/a/Sites/boards-io/target/test/out/","/Users/a/.node_modules","/Users/a/.node_libraries","/Users/a/.nvm/versions/node/v6.3.1/lib/node"]
module.js:442
    throw err;
    ^

Error: Cannot find module 'react'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at /Users/a/Sites/nodejs-cljs/out/react-dom.inc.js:16:24
    at Object.<anonymous> (/Users/a/Sites/nodejs-cljs/out/react-dom.inc.js:40:3)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
```

**Comment by kommen** [comment]
@alex-glv we're running into the same issue here. Have found anything in the meantime?

**Comment by ducky427** [comment]
I think this may be related to a [CLJS issue](http://dev.clojure.org/jira/browse/CLJS-1883)

**Comment by alex-glv** [comment]
@kommen Install react from npm first, then react-dom finds it alright.

**Comment by kommen** [comment]
@alex-glv yep, we did that and it worked. Thanks!
